name: Daily Email Sender

on:
  schedule:
    # Runs daily at 8 AM UTC
    - cron: '0 8 * * *'
    - cron: '0 12 * * *'
    - cron: '0 16 * * *'
    - cron: '0 20 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Add credentials.json
      run: echo "$GMAIL_CREDENTIALS" > credentials.json
      env:
        GMAIL_CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}

    - name: Add token.json (if provided)
      run: |
        if [ -n "$TOKEN_JSON" ]; then
          echo "$TOKEN_JSON" > token.json
        fi
      env:
        TOKEN_JSON: ${{ secrets.TOKEN_JSON }}

    - name: Run email script
      run: python send_email.py
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
